### ISSUE TITLE
[Question - Not an issue] Using markets

### ISSUE THREAD

**Issue by digital-inception** [sanity-io/demo-marketing-site-nextjs#48]
Is it possible to use this repo and remove everything related to market?
I want to use it for a client but he does not want the markets part of it.

**Comment by multiplehats** [comment]
Why wouldn't it be @digital-inception ? You can take parts of it and reuse it as inspo, no?

**Comment by digital-inception** [comment]
> Why wouldn't it be @digital-inception ? You can take parts of it and reuse it as inspo, no?

Thanks @multiplehats. Exactly what I started doing

**Comment by multiplehats** [comment]
> > Why wouldn't it be @digital-inception ? You can take parts of it and reuse it as inspo, no?
> 
> 
> 
> Thanks @multiplehats. Exactly what I started doing

Way to go! Good luck 👏
